### ISSUE TITLE
Configuration lists $authMgrPlus_role_assignment instead of $amp_role_assignment

### ISSUE THREAD

**Issue by camro** [joshp23/YOURLS-AuthMgrPlus#10]
The configuration instructions list the configuration variable as $authMgrPlus_role_assignment, which is not found in plugin.php and doesn't work, instead of $amp_role_assignment which does work.

Suspect it is the same with authMgrPlus_allowed_plugin_pages and authMgrPlus_admin_ipranges

**Comment by joshp23** [comment]
Correct. See https://github.com/joshp23/YOURLS-AuthMgrPlus/issues/9#issuecomment-547766969
