### ISSUE TITLE
When migrating to this plugin, existing short links are visible to all users

### ISSUE THREAD

**Issue by vmario89** [joshp23/YOURLS-AuthMgrPlus#13]
Hi,
i was running yourls for 2 years. Now i added AuthMgrPlus what is really nice and does what it should!

I recognized that already existing shortened URLs are visible for other users. I had to fix this manually by updating database entries in MySQL (did it with sql developer).

Could you please add some side note for users who are migrating, like me?

regards and thanks for your work!

**Comment by joshp23** [comment]
I might do that. I'm thinking of putting in an interface in admin to accomplish this with the click of a button.

**Comment by joshp23** [comment]
put in README :)
