### ISSUE TITLE
Redirects throwing HTTP 500 error

### ISSUE THREAD

**Issue by vmario89** [joshp23/YOURLS-AuthMgrPlus#14]
Hi,
the backend thing works well to separate permissions. But now i recognized after isntallation and configuration: the URLs stop working when plugin is enabled. It throws HTTP 500 error

it works when disabling AuthMgrPlus

I guess it belongs to the issue of supporting 1.7.4 (because readme shows up until 1.7.3)

regards, Mario

**Comment by joshp23** [comment]
Fixed in https://github.com/joshp23/YOURLS-AuthMgrPlus/commit/33a551c1b12856111ec44740482e738d87d85200. Nothing to do with 1.7.4 compatibility. Readme updated.

**Comment by joshp23** [comment]
This was the issue
https://github.com/joshp23/YOURLS-AuthMgrPlus/commit/33a551c1b12856111ec44740482e738d87d85200#diff-262e5e7eb7bc31022b9eb9a5df4a620eR355

**Comment by vmario89** [comment]
thanks for the quick fix :-D
