### ISSUE TITLE
Can't delete or edit own links being other than an administrator.

### ISSUE THREAD

**Issue by plablo** [joshp23/YOURLS-AuthMgrPlus#15]
Good morning. The plugin is amazing but I'm having a weird issue with roles. As the title says, here is my problem:

- Being a _collaborator_ **can't** delete my own links.
- Being an _editor_ **can't** delete my own or "collaborators" links.
- Being an _administrator_ **can** delete or modify everything.

I followed the configuration from Readme, writing something like this:

`$amp_role_assignment = array(
  'administrator' => array(
    'user1'
  ),
  'editor' => array(
	'user2'
  ),
  'contributor' => array(
	'user3'
  )
);`

If, for example, I move _user2_ to the _administrator_ array then I can delete links, not otherwise.

Any ideas? Thank you in advance. 😄

**Comment by holzhannes** [comment]
I can confirm this error exist also for my Installation.

**Comment by joshp23** [comment]
I've looked into this and I think I've isolated the problem. however I'm quite busy AFK at this time. I encourage pull requests.

**Comment by sathish1981** [comment]
@joshp23 @plablo : I am facing the same problem too. Editor and contributor cannot edit their own links. Any solution would be greatly helpful.

**Comment by joshp23** [comment]
Apologies this took so long to address. Latest (2.1.2) addresses this.
