### ISSUE TITLE
Blank Page for contributors

### ISSUE THREAD

**Issue by CoolZeus** [joshp23/YOURLS-AuthMgrPlus#18]
i just installed it and have account for each section while admin and edior accounts are working fine contributor account is throwing blank page. and here is the error log just after login with a contributor account:
`[Wed May 20 11:24:23.749859 2020] [proxy_fcgi:error] [pid 29491:tid 140412371052288] [client 127.0.0.1:39160] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'user' in 'where clause' in /home/url/includes/vendor/aura/sql/src/ExtendedPdo.php:748\nStack trace:\n#0 /home/url/includes/vendor/aura/sql/src/ExtendedPdo.php(748): PDOStatement->execute()\n#1 /home/url/includes/vendor/aura/sql/src/ExtendedPdo.php(484): Aura\\Sql\\ExtendedPdo->perform('SELECT COUNT(ke...', Array)\n#2 /home/url/user/plugins/authmgrplus/plugin.php(346): Aura\\Sql\\ExtendedPdo->fetchObject('SELECT COUNT(ke...', Array)\n#3 /home/url/includes/functions-plugins.php(150): amp_get_db_stats(Array, Array)\n#4 /home//url/includes/functions.php(694): yourls_apply_filter('get_db_stats', Array, Array)\n#5 /home/url/admin/index.php(151): yourls_get_db_stats()\n#6 {main}\n  thrown in /home/...', referer: url/admin/?action=logout`

I have whatsoever no idea if it's related to plugin or something is wrong in y end.

**Comment by CoolZeus** [comment]
Solved, the plugin activation played some trick resulting the db not being altered, i manually altered the db and it's start showing all my links as of now i will try to update them all by using my username instead of null.

**Comment by joshp23** [comment]
I wonder what caused the trick. I updated the plugin for a (hopefully) more reliable activation.
