### ISSUE TITLE
YOURLS-AuthMgrPlus intervening on AJAX

### ISSUE THREAD

**Issue by danilorassis** [joshp23/YOURLS-AuthMgrPlus#19]
Hello. I am using the plugin to restrict access to only a few users. However, when I activate the plugin, AJAX does not update the table on the page. It does not insert or delete action. What can it be? If I turn it off, everything goes back to normal

Show this warnning
Warning: Invalid argument supplied for foreach() in /var/www/yourls/user/plugins/yourls-authmgrplus/plugin.php on line 164

Warning: sort() expects parameter 1 to be array, null given in /var/www/yourls/user/plugins/yourls-authmgrplus/plugin.php on line 173

The create short url button looks like this.

![image](https://user-images.githubusercontent.com/43686865/83281954-43f99400-a1af-11ea-8022-5ddfb8e0e6e2.png)

**Comment by joshp23** [comment]
The lines referred to by those errors are concerned with limiting access to plugin admin pages for unauthorized users. I'm not sure what might be causing your issue, as I am not able to reproduce the error. More information regarding your environment, or some error log info would help provide some direction.

**Comment by joshp23** [comment]
Looking into this briefly, it appears as if the admin links are blank in your installation before this plugin attempts to filter them. 
1. Are you using any other plugins that alter the links in the admin page? 
2. Does this error occur when ONLY this plugin is enabled, and no other plugins?

**Comment by justinforlenza** [comment]
I am also getting this error on 1.7.9, i tried it with only AuthMgrPlus enabled, and still am getting the issue.

**Comment by joshp23** [comment]
> Warning: sort() expects parameter 1 to be array, null given in /var/www/yourls/user/plugins/yourls-authmgrplus/plugin.php on line 173

Addressed with 09ab9fd0e6593bd144470403b6de7698c4275622 and related to #30

>  Warning: Invalid argument supplied for foreach() in /var/www/yourls/user/plugins/yourls-authmgrplus/plugin.php on line 164

Addressed with https://github.com/joshp23/YOURLS-AuthMgrPlus/commit/93b4a263c3608c777c43ebdd8bc5fc1ee73595e5
