### ISSUE TITLE
Display users in Admin Interface

### ISSUE THREAD

**Issue by sathish1981** [joshp23/YOURLS-AuthMgrPlus#20]
@joshp23 
I am a fan of your plugin :) it works great!
Is it possible to display Users in Admin interface, Search & Sort? 
This will make the list looks perfect and easy to manage. Let me know the possibilities.

**Comment by robertskiba** [comment]
I would also be interested! A separate column to see which user created which link would be very nice!

**Comment by joshp23** [comment]
duplicate of #8
