### ISSUE TITLE
I think I am missing something

### ISSUE THREAD

**Issue by hoochalaffa** [joshp23/YOURLS-AuthMgrPlus#21]
Hi,

Maybe this isn't the right place to post this, I am new to YOURLS. Does this plugin depend on another plugin to create new users? I am lost trying to add additional users.

Any help is appreciated.

**Comment by syrac88** [comment]
I have the same problem. Im using yourls 1.7.2 and the plugin does nothing. No new buttons, settings or anything else.
Is this broken,  or am I doing something wrong?

**Comment by sathish1981** [comment]
@hoochalaffa 
First you need to create the user in config.php as per YOURLS documentation

Then by using this plugin you can assign the roles. This plugin used only for assigning the roles not for creating users. 
For role assignment check readme section of this plugin.

This is a cool plugin... you will luv it :) 👍 💯

**Comment by joshp23** [comment]
I have been kicking around total user management with this plugin, merging somewhere with my OIDC plugin. If I get around to it ;)
