### ISSUE TITLE
version number in code is incorrect - should be 2.3.4

### ISSUE THREAD

**Issue by clmcavaney** [joshp23/YOURLS-AuthMgrPlus#28]
G'day,

Was about to apply this new version today and noticed the version number in the code itself is not correct:
https://github.com/joshp23/YOURLS-AuthMgrPlus/blob/5d37ab7c4d53e301f139a4b0d7d0cfc01ec72f12/authMgrPlus/plugin.php#L6

I think it should be 2.3.4

Regards,
Christopher

**Comment by joshp23** [comment]
other way around, as it turns out. tag and release fixed.
