### ISSUE TITLE
YOURLS 1.8 and AuthMgrPlus produce Argument #1 ($array) must be of type array

### ISSUE THREAD

**Issue by Andyt8** [joshp23/YOURLS-AuthMgrPlus#30]
Hello,

I upgraded to YOURLS 1.8 with PHP8. I found a problem with enabled AuthMgrPlus. The Dashboard work without problem. Also using the short url.

However, if I want to open the statistics page for a short url, I see an empty page (except background and logo). It work after disabling of AuthMgrPlus. Switching back to PHP7.4 doesn't change anything.

According to php log, I fount the following:
Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: sort(): Argument #1 ($array) must be of type array, null given in /user/plugins/authMgrPlus/plugin.php:171\nStack trace:\n#0

Please for response.

**Comment by Andyt8** [comment]
It does look like that the problem isn't YOURLS 1.8 or 1.8.1- the main problem is PHP8. Some disadvantage with modern Webspace hosting. However, according to the Readme, AuthMgrPlus is only compatible with PHP7. Is there a change, that there will be a version for PHP8?

best regards

**Comment by Andyt8** [comment]
In detail, it has something to do with "sort( $links['plugin']);" in line 171. If I remove or set a comment for the function, I see no error and get a statistic page.

**Comment by joshp23** [comment]
Actually, I think the issue might be related to the `$links['plugins']` array on line 171 possibly being empty in your setup. Try this:
Starting at line 168
```
	if( empty( $links['plugins'] ) )
		yourls_add_filter( 'admin_links', 'amp_admin_links' );
		
	sort($links['plugins']);
	return $links;
```
With this
```
	if( empty( $links['plugins'] ) )
		unset($links['plugins']);
	else
		sort($links['plugins']);
	return $links;
```

**Comment by Andyt8** [comment]
Perfectly, that work for me. Thank you.
