### ISSUE TITLE
Integration with OIDC

### ISSUE THREAD

**Issue by Swampcritter** [joshp23/YOURLS-AuthMgrPlus#33]
How does one integrate this plugin with the YOURLS-OIDC plugin?

**Comment by abdennour** [comment]
it should work outofthebox
I am using keycloak & this plugin . and it works.

However, i notice that no once can access /admin only whoever has administrator role.
All other roles, i got : 
Require permissions to show admin interface.

**Comment by joshp23** [comment]
@Swampcritter, out of the box it should work. Just link the username to an OIDC identity, and also to a role. 

@abdennour, that is odd. please see the following:
 https://github.com/joshp23/YOURLS-AuthMgrPlus/blob/d7d5d00b78b077eb69a5adfa0417538c0c7d2552/authMgrPlus/plugin.php#L415-L454
That gives all roles besides anon access to admin.
