### ISSUE TITLE
$amp_default_role appears to override $amp_role_assignment

### ISSUE THREAD

**Issue by oskapt** [joshp23/YOURLS-AuthMgrPlus#34]
I've spent several hours with this, and it's possible I'm misunderstanding something.

I run YOURLS as a container under Kubernetes, with configuration handled via env vars or Secrets stored as JSON and then parsed with `json_decode` in `config.php`. That all works fine, but it's the reason I'm including JSON here.

I have this:

```
{
    "administrator": [
        "oskapt",
    ],
    "editor": [
        "weasel"
    ],
    "contributor": [
    ]
}
```

I also have `$amp_default_role` set to `Contributor`.

The "oskapt" user is correctly assigned as an administrator. The "weasel" user is assigned as an Editor. All is good.

If I switch it to this:

 ```
{
    "administrator": [
        "oskapt",
    ],
    "editor": [
    ],
    "contributor": [
        "weasel"
    ]
}
```

and set `$amp_default_role` to `Editor` then the "weasel" user can see entries made by other people as an Editor.

If I remove support for `$amp_default_role` entirely, then "weasel" is correctly assigned the Contributor or Editor role according to `roles.json`.

It looks a lot like `$amp_default_role` is not being limited to non-configured users but is instead acting as a floor, beneath which all users receive elevated privileges.

**Comment by joshp23** [comment]
the issue would be in this logic
https://github.com/joshp23/YOURLS-AuthMgrPlus/blob/475417ff91807d7020fa3dc3b3150bfb6b1607e7/authMgrPlus/plugin.php#L290-L295
and reading it over, it is clearly in error. I would just comment this section out for now unless you are capable of fixing the error.

**Comment by joshp23** [comment]
latest commit should fix this
