### ISSUE TITLE
Problem with new Shortlinks. user name is not saved. Everybody can see all created links

### ISSUE THREAD

**Issue by robertskiba** [joshp23/YOURLS-AuthMgrPlus#35]
Hi Josh,

I currently have a problem with version 2.3.0 of your plugin. 

the problem is, that it doesn't save the name of the user who created the link anymore, so everybody can see the created shortlink. 

thats a big problem for my system. 

could you check it please?

I'm running Yourls 1.8.1 of course. 

3 users

It also doesn't work if I turn off all of my other plugins

**Comment by developer505** [comment]
Also getting this issue.  
Every new link added, no matter if the user is an admin, editor or contributor, they still don't save the username.

**Comment by mwehr** [comment]
Hi,

Revert Line #593 of [commit](https://github.com/joshp23/YOURLS-AuthMgrPlus/commit/37c769d44b94b47fe64a734b01248eba73fa253f) to fix the problem.

**Comment by joshp23** [comment]
iirc reverting that line introduces another problem into the database on my setup. it's a good workaround for now.

**Comment by nekto198** [comment]
> Hi,
> 
> Revert Line #593 of [commit](https://github.com/joshp23/YOURLS-AuthMgrPlus/commit/37c769d44b94b47fe64a734b01248eba73fa253f) to fix the problem.

It doesn't work anyway

**Comment by DeveloperPad** [comment]
The reason for this bug is a typo with missing quotes.
Change
`$user = defined(YOURLS_USER) ? YOURLS_USER : NULL;`
to
`$user = defined('YOURLS_USER') ? YOURLS_USER : NULL;` (quotes around "YOURLS_USER")
to fix this issue.

**Comment by joshp23** [comment]
fixed with e3cb3401c1d1c57f37d4b36465a4a84dc0707e4e
