### ISSUE TITLE
Changing Role Capabilities

### ISSUE THREAD

**Issue by lyrixn** [joshp23/YOURLS-AuthMgrPlus#36]
Do I need to change the plugin to edit permissions under $amp_role_capabilities or can I overwrite the array somehow using config.php?

**Comment by joshp23** [comment]
You can set your own. Look to https://github.com/joshp23/YOURLS-AuthMgrPlus/blob/475417ff91807d7020fa3dc3b3150bfb6b1607e7/authMgrPlus/plugin.php#L416 for inspiration
