### ISSUE TITLE
How to make other plugins respect AuthMgrPlus?

### ISSUE THREAD

**Issue by skeith** [joshp23/YOURLS-AuthMgrPlus#38]
Hi

Is there any guide or documentation on how can I make other YOURLS plugins to respect AuthMgrPlus user assignment?

**Comment by joshp23** [comment]
Is there a use case? Just have your other plugin call the function here
https://github.com/joshp23/YOURLS-AuthMgrPlus/blob/475417ff91807d7020fa3dc3b3150bfb6b1607e7/authMgrPlus/plugin.php#L250
or have your other plugin refer to `$amp_role_assignment` that should be defined in your `YOURLS/user/config.php`
