### ISSUE TITLE
$amp_role_assigment

### ISSUE THREAD

**Issue by mynameistito** [joshp23/YOURLS-AuthMgrPlus#47]
Hi Team, 

Been having an issue with the role assign and still getting the 

> Require permissions to show admin interface.

error
```

$amp_default_role = "Editor";
$amp_role_assignment = array(
  'administrator' => array(
    'Tito',
    'tito',
  ),
  'editor' => array(
    'your_close_friend',
  ),
  'contributor' => array(
    'your_other_friend',
  ),
);
```
is a code snipet idk if I'm just being stupid or not lol any help would be appreciated.

**Comment by opl-git** [comment]
Same problem here. 
@MyNameIsTito : Could you solve it?

**Comment by mynameistito** [comment]
nah no fix on my end @opl-git

**Comment by opl-git** [comment]
@joshp23 Could you help us, please? A fix would be very much appreciated.

**Comment by mynameistito** [comment]
not 100% @opl-git but I think https://github.com/joshp23/YOURLS-AuthMgrPlus/pull/31 Fixes it

**Comment by TheRayJohnson** [comment]
Can confirm #31 fixed it for me. Can now login no more `Require permissions to show admin interface.` white page error.

Running YOURLS v1.9.
