### ISSUE TITLE
Incompatibility with Sleeky theme

### ISSUE THREAD

**Issue by easysoft-mobility** [joshp23/YOURLS-AuthMgrPlus#9]
AuthMgrPlus plugin is really useful for me as same as Flynntes's Sleeky theme but it seems to not be compatible with Sleeky theme as nothing work. All user continue to have full access regardless of role assigned.
Could you please look at that for me. I'm mobile developer, I'm still noob in web development.
Here link of Sleeky theme: https://github.com/Flynntes/Sleeky

**Comment by sabweb** [comment]
I just had the same issue, it's independent from the theme you use.  Did you install AuthMgrPlus recently? The names of the main configuration variables were changed about a month ago (see [this commit](https://github.com/joshp23/YOURLS-AuthMgrPlus/commit/7e2aba130d4d3e32d93a9894f2d172e3c75e175b)), but the documentation isn't updated yet. So you have to use `$amp_role_assignment... ` instead of `$authMgrPlus_role_assignment` in your user/config.php file.

**Comment by joshp23** [comment]
good catch, @sabweb. I've been working afk quite a bit lately and apparently missed this one. I'll update the README soon.

**Comment by easysoft-mobility** [comment]
> I just had the same issue, it's independent from the theme you use. Did you install AuthMgrPlus recently? The names of the main configuration variables were changed about a month ago (see [this commit](https://github.com/joshp23/YOURLS-AuthMgrPlus/commit/7e2aba130d4d3e32d93a9894f2d172e3c75e175b)), but the documentation isn't updated yet. So you have to use `$amp_role_assignment... ` instead of `$authMgrPlus_role_assignment` in your user/config.php file.

Yeah ! It worked. Thanks a lot !

**Comment by easysoft-mobility** [comment]
> good catch, @sabweb. I've been working afk quite a bit lately and apparently missed this one. I'll update the README soon.

Super !
As an improvement, could you please make Plugins's button hidden in admin area when user does'nt have right to manage plugins.
I think it'll be more efficient than simply showing "Access Denied" alert.
Or if you can help me make this change with codes, as I waiting for these improvement to launch my bit.ly like website... I'm learning php but still noob.
Thanks to all !

**Comment by easysoft-mobility** [comment]
Another suggestion is to make user see only it's own url. At this time, my Contributor's role based user are seeing all url but cannot delete others's url.

**Comment by easysoft-mobility** [comment]
As an alternative workaround, you could help me make stats page accessible to all with no need to login. This assume that we have to hide all menu links that points to admin dashbord etc...
Thank a lot !

(I this time in my learning, I'm just able to design programmatically php and html pages, no more than that for now...)

**Comment by joshp23** [comment]
https://github.com/joshp23/YOURLS-AuthMgrPlus/commit/339585721e89b1891fc3a39997e58df41ef967ef addresses this issue
----------------
Otherwise, the separate requests should be made issues of their own. Thanks.
